name: Build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v2
      - name: Lint
        run: pnpm lint
      - name: Check formatting
        run: pnpm fmt:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v2
      - name: Test
        run: pnpm test
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: mskelton/setup-pnpm@v2
      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
